SELECT
    uid,
    last_name,
    first_name,
    aliases,
    low_quality_aliases,
    alternative_spelling,
    category,
    title,
    `sub-category` AS sub_category,
    position,
    age,
    dob as date_of_birth,
    dobs as date_of_births,
    place_of_birth,
    deceased,
    passports,
    ssn,
    identification_numbers,
    locations,
    countries,
    citizenship,
    companies,
    `e/i` AS e_i,
    linked_to,
    further_information,
    keywords,
    external_sources,
    update_category,
    editor,
    `age_date_(as_of_date)` as age_date,
    pep_roles,
    pep_status,
    special_interest_categories,
    {{ to_utc_date_if_not_null('entered') }} as created_at,
    {{ to_utc_date_if_not_null('updated') }} as updated_at,
    toTimeZone(now64(), 'UTC') as inserted_at
FROM
    `premium-world-check-full-synthetic`
